import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import Link from "next/link";

const alata = Alata({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: { children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={alata.className}
            >
                <NavigationMenu className="py-4 pl-8">
                    <NavigationMenuList>
                        {[
                            { name: "Home", path: "/" },
                            { name: "Quiz", path: "/quiz" },
                            { name: "Profile", path: "/profile" }
                            
                        ].map(({ name, path }) => (
                                <NavigationMenuItem key={name}>
                                    <Link href={path} passHref>
                                    <p className=" text-[#26235E] text-4xl font-alata opacity-90 px-8 py-2 mt-5 mb-0 ml-8 bg-white rounded-full hover:text-white hover:bg-[#26235E] transition duration-700">
                                            {name}
                                        </p>
                                    </Link>
                                </NavigationMenuItem>
                            ))}
                    </NavigationMenuList>        </NavigationMenu>

                {children}
            </body>
        </html>
    );
}
